name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  metrics-left:
    runs-on: ubuntu-latest
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg
          
          # Options
          user: AnyaReese
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          
          # Plugins
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_ignored: html
          plugin_languages_details: bytes-size, percentage
          plugin_languages_aliases: Jupyter Notebook:ipynb
          plugin_starlists: yes
          plugin_followup: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_repositories: 0
          plugin_starlists_limit_languages: 8
          plugin_starlists_only: "ToLearn"
          
          # Followup 插件完整配置
          plugin_followup_sections: user
          plugin_followup_indepth: no
          
          config_order: followup, languages, starlists

  metrics-right:
    runs-on: ubuntu-latest
    steps:
      - name: right
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg

          # Options
          user: AnyaReese
          template: classic
          base: repositories
          config_timezone: Asia/Shanghai
          
          # Plugins
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
        #   plugin_topics_sort: stars
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          config_order: header, activity, community, repositories, metadata, topics, isocalendar
          